#!/usr/bin/env python3
"""Regenerate videos/manifest.js by scanning the gallery folders.
Run this after adding/removing/renaming any clip under static/videos/.
Usage:  python static/js/gen_manifest.py   (run from the page/ folder)

Layout
------
static/videos/
  v2a/<name>.mp4     video-to-audio samples
  a2v/<name>.mp4     audio-to-video samples
  cjavg/<name>.mp4   joint audio-video samples

Each clip is a single "sounding video" (.mp4 carrying both video and audio).
"""
import os, json
BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "videos"))
FLAT_TASKS = ["v2a", "a2v", "cjavg"]
VIDEO_EXT = (".mp4", ".webm", ".mov")

def label(fn):
    return os.path.splitext(fn)[0].replace("data@vggsound@", "").replace("_", " ")

def list_videos(d):
    if not os.path.isdir(d):
        return []
    return sorted(f for f in os.listdir(d) if f.lower().endswith(VIDEO_EXT))

data = {}

# --- flat single-video galleries -------------------------------------------
for t in FLAT_TASKS:
    vids = list_videos(os.path.join(BASE, t))
    data[t] = [{"src": f"static/videos/{t}/{f}", "label": label(f)} for f in vids]
    print(f"{t}: {len(data[t])} clips")

out = os.path.join(BASE, "manifest.js")
with open(out, "w") as f:
    f.write("// Auto-generated by static/js/gen_manifest.py — do not edit by hand.\n")
    f.write("// Re-run that script whenever you change the clips under static/videos/.\n")
    f.write("window.AVTOK_GALLERIES = " + json.dumps(data, indent=2) + ";\n")
print("wrote", out)
